# Generated by Django 4.0.2 on 2022-02-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passcode',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=None),
        ),
    ]
