# Generated by Django 4.0.2 on 2022-02-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_passcode_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcode',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
