# Generated by Django 4.0.2 on 2022-02-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_passcode_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passcode',
            old_name='pass_code',
            new_name='passcode',
        ),
    ]
