# Generated by Django 4.0.2 on 2022-02-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text2html', '0006_alter_editor_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passcode',
        ),
    ]
